document.writeln("<div class=\'index-footer box\'>");
document.writeln("    <div class=\'index-cop\'>合作媒体：");
document.writeln("        <div>");
document.writeln("            <ul>");
document.writeln("                <li><img src=\'img/163.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/baidu.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/fh.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/qq.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/sina.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/sohu.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/163.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/baidu.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/fh.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/qq.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/sina.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/sohu.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/163.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/baidu.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/fh.jpg\' alt=\'\'></li>");
document.writeln("                <li><img src=\'img/qq.jpg\' alt=\'\'></li>");
document.writeln("");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <hr data-am-widget=\'divider\' style=\'width:70% \' class=\'am-divider am-divider-default\'/>");
document.writeln("    <div class=\'copyright\'>COPYRIGHT © 2017 <p>版权所有：兆讯传媒有限公司</p></div>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<script src=\'js/bootstrap.min.js\'></script>");
document.writeln("<script src=\'js/amazeui.min.js\'></script>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");