document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
    document.writeln("    <meta charset=\'utf-8\'>");
    document.writeln("    <meta name=\'renderer\' content=\'webkit\'>");
    document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
    document.writeln("    <meta name=\'viewport\'");
                                document.writeln("          content=\'width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\'>");
    document.writeln("    <title>首页--兆讯传媒</title>");
    document.writeln("    <link rel=\'stylesheet\' href=\'css/amazeui.min.css \'>");
    document.writeln("    <link rel=\'stylesheet\' href=\'css/bootstrap.css\'>");
    document.writeln("    <link rel=\'stylesheet\' href=\'css/index.css\'>");
    document.writeln("    <link rel=\'stylesheet\' href=\'css/s-page.css\'>");
    document.writeln("<script src=\'js/jquery-3.2.1.min.js\'></script>");
    document.writeln("<script src=\'js/config.js\'></script>");
    document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<!--头部部分-->");
document.writeln("<div class=\'index-header\'>");
    document.writeln("    <div class=\'index-header-login box\'>");
    document.writeln("        <ul>");
        document.writeln("            <li><span class=\'glyphicon glyphicon-user\'></span> <a href=\'\'>注册</a></li>");
        document.writeln("            <li><a href=\'\'>登录</a></li>");
        document.writeln("            <li><span class=\'glyphicon glyphicon-shopping-cart\'></span> <a href=\'\'>购物车</a></li>");
        document.writeln("        </ul>");
    document.writeln("    </div>");
document.writeln("    <div class=\'index-header-logo box\'>");
document.writeln("        <div class=\'index-header-logo-img\'><img src=\'\' alt=\'\'></div>");
document.writeln("        <div class=\'index-header-logo-search\'>");
    document.writeln("            <div class=\'input-group\'>");
        document.writeln("                <span class=\'glyphicon glyphicon-search input-group-addon\'></span>");
        document.writeln("                <input type=\'text\' name=\'\' class=\'index-hear-seach\' placeholder=\'请输入你要搜索的关键字\'>");
        document.writeln("                <input type=\'submit\' value=\'搜索\' class=\'btn index-hear-seach-bnt\'>");
        document.writeln("            </div>");
    document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");